/* GENERATED by tools/extract-besorah.js --emit — do not hand-edit.
   THE SPINE OF EVERY SCROLL ON THE SHELF, and nothing else. The books
   themselves are fetched one at a time, when one is taken down to read;
   this is the only part of the scripture the page loads at boot, so that
   the shelf can be drawn and a passage named before a word of it is read. */
BESORAH.index([{"id":"adam-eve-1","hebrew":"ADAM AND HAWWAH 1","english":"First Book of Adam and Eve","chapters":79},{"id":"adam-eve-2","hebrew":"ADAM AND HAWWAH 2","english":"Second Book of Adam and Eve","chapters":22},{"id":"bereshith","hebrew":"BERĔSHITH","english":"Genesis","chapters":50},{"id":"chanok-eth","hebrew":"ḤANOḴ HABASHIY","english":"Enoch (Ethiopic)","chapters":108},{"id":"chanok","hebrew":"ḤANOḴ","english":"Enoch","chapters":25},{"id":"shamoth","hebrew":"SHAMOTH","english":"Exodus","chapters":40},{"id":"yashar","hebrew":"YASHAR","english":"Jasher","chapters":91},{"id":"yobelim","hebrew":"YOḆELIM","english":"Jubilees","chapters":50}]);
