/* ACT VI — PASSION WEEK. The design document: "The triumphal entry; cleansing the Temple; the
   Passover supper and the washing of feet; Gethsemane; Yahudah's betrayal; the trials;
   Golgotha; the tomb. Codex lights: 53 (the Suffering Servant — the emotional peak of the whole
   game)."

   THE WITNESS has come up to the city with them for the Pesach. He spreads a branch on the way,
   carries the basin up to the upper room and keeps its door through the supper, holds the lamp
   at the gate of the garden, stands at the fire in the courtyard of the kohen gadol, stands with
   the women at a distance at Golgotha, and carries Naḵdimon's spices to the tomb and puts his
   shoulder to the stone. He never speaks in a named mouth, and nothing he does changes what the
   Besorah says happened.

   THE ORDER: the entry (Mattithyahu 21:8-11; Mark 11:11); the House cleared and the children's
   Hoshia-na (Mark 11:15-18; Mattithyahu 21:14-16); Caesar's coin and the widow's two coins (Mark
   12:13-17, 41-44); the anointing at Bĕyth Anyah and Yahuḏah's going (Mark 14:1-11); the
   Pesach prepared (Luke 22:7-13); the supper — the feet washed (Yahuchanon 13:1-15), "one of you"
   (Mattithyahu 26:21-25; Yahuchanon 13:23-30), the bread and the cup (Mattithyahu 26:26-29), the
   renewed command (Yahuchanon 13:34-35); Gethsemane (Mark 14:26-42; Luke 22:43-44); the arrest
   (Mark 14:43-50; Yahuchanon 18:4-13; Luke 22:48-51); the night in the courtyard of the kohen
   gadol (Mark 14:53-70; Luke 22:59-62); Pilate (Yahuchanon 18:28-19:16; Mattithyahu 27:19, 24-25);
   Golgotha (Luke 23; Yahuchanon 19; Mark 15:33-39); the tomb (Yahuchanon 19:31-42; Luke 23:50-56;
   Mattithyahu 27:60-66).

   REVERENCE. Yahusha's face is never shown, on the road, at the table, in the garden, before
   Pilate, on the stake or in the tomb: the camera is behind Him, at His hands and robe, or far
   off. What was done to Him — the flogging, the blows, the spear — is read, never drawn; the
   camera is on those who watched. The fallen are not shown here: the Besorah says Satan entered
   Yahuḏah, and that is read. */
(function(){
const ADULT={robe:0x8a7454, cloth:0xd8cfb8, beard:0x3a2a1e, skin:0x86573a};
const YAHUSHA={name:'Yahusha', holy:true, kind:'yahusha', key:'Yahusha'};
const T12={
  kepha:{name:'Shim‛on Kĕpha', key:'Shim‛on Kĕpha', robe:0x6e5238, cloth:0xb9ab8e, beard:0x3a2a1e, skin:0x6e4524},
  andri:{name:'Andri', key:'Andri', robe:0x5a6a7a, cloth:0xd8ceb4, beard:0x3a2a1e, skin:0x704a27},
  yaaqob:{name:'Ya‛aqoḇ', key:'Ya‛aqoḇ son of Zaḇdai', robe:0x7a3a2a, cloth:0xcfc4aa, beard:0x2c241f, skin:0x7a4e29},
  yahuchanon:{name:'Yahuchanon', key:'Yahuchanon son of Zaḇdai', robe:0x4a5a3a, cloth:0xe6e0cf, skin:0x855a33},
  philip:{name:'Philip', key:'Philip', robe:0x6a5a7a, cloth:0xd8ceb4, beard:0x2c241f, skin:0x7c5430},
  bartholomi:{name:'Bartholomi', key:'Bartholomi', robe:0x6a5a44, cloth:0xd8ceb4, beard:0x2c241f, skin:0x7a4e29},
  mattithyahu:{name:'Mattithyahu', key:'Mattithyahu', robe:0x4a5a6a, cloth:0xe6e0cf, beard:0x2c241f, skin:0x855a33},
  toma:{name:'T’oma', key:'T’oma', robe:0x7a6a4a, cloth:0xcfc4aa, beard:0x3a2a1e, skin:0x6e4524},
  yaaqobA:{name:'Ya‛aqoḇ the son of Alphai', key:'Ya‛aqoḇ the son of Alphai', robe:0x5a4a3a, cloth:0xd8ceb4, beard:0x1e1814, skin:0x704a27},
  shimonZ:{name:'Shim‛on the Ardent One', key:'Shim‛on the Ardent One', robe:0x7a3a2a, cloth:0xb9ab8e, beard:0x2c241f, skin:0x5c3a1f},
  yahudahY:{name:'Yahuḏah the son of Ya‛aqoḇ', key:'Yahuḏah the son of Ya‛aqoḇ', robe:0x5f6a52, cloth:0xe6e0cf, beard:0x3a2a1e, skin:0x7c5430},
  yahudahQ:{name:'Yahuḏah from Qerioth', key:'Yahuḏah from Qerioth', robe:0x6e5a70, cloth:0xcfc4aa, beard:0x1e1814, skin:0x8a6038}
};
const T=(id,at,extra)=>Object.assign({id,at},T12[id],extra||{});
const TWELVE=Object.keys(T12);
const MIRYAM={name:'Miryam', key:'Miryam', robe:0x3f5a8a, cloth:0xe8e2d2, skin:0x8e5c3c, kind:'woman'};
let seed=37; const rnd=()=>(seed=(seed*16807)%2147483647)/2147483647;
const ROBES=[0x7c6a52,0x5f6a52,0x8e6f4c,0x6b5a44,0x74604a,0x5c5040,0x8a7a60,0x6e5a70,0x7a5040,0x5a6470,0x8a5a3a,0x4f6a4f];
const CLOTHS=[0xcfc4aa,0xd8ceb4,0xb9ab8e,0xe6e0cf,0xc1b394,0xa89a7e];
function folk(pre,n,area,face,o){
  const out=[];
  for(let k=0;k<n;k++){ const woman=k%3===1;
    out.push(Object.assign({id:pre+k, at:[area[0]+rnd()*(area[2]-area[0]), area[1]+rnd()*(area[3]-area[1])],
      face:face+(rnd()-0.5)*0.9, robe:ROBES[(k*7+pre.length)%ROBES.length], cloth:woman?[0xe8e2d2,0x3c3a44,0x8a6a5a][k%3]:CLOTHS[(k*5)%CLOTHS.length],
      beard:!woman&&k%4!==0?[0x2c241f,0x3a2a1e,0x6d6a66,0x1e1814][k%4]:null, kind:woman?'woman':'man'},o||{})); }
  return out;
}
const ids=list=>list.map(a=>a.id);
const LEGION=(id,at,face,extra)=>Object.assign({id,at,face,folk:'roman',dress:'legionary'},extra||{});

/* the crowds of each scene */
const GATECROWD=folk('g',18,[-20,40,-8,52],Math.PI*0.5);                       /* at the gate (Mattithyahu 21:8) */
const SELLERS=folk('v',6,[-34,-57,-18,-53],Math.PI);                           /* buying and selling in the court */
const COURTFOLK=folk('c',10,[-22,-56,-12,-51],Math.PI);
const KIDS=[0,1,2,3].map(k=>({id:'kid'+k, name:k?undefined:'The children', kind:k%2?'woman':'boy', small:true, at:[-14+k*1.3,-51], face:Math.PI, robe:[0x9a5a62,0x6a7a5a,0x9a7a5a,0x5a6a8a][k], cloth:[0xe0c27a,0xe6e0cf,0xd8cfb8,0xe8e2d2][k]}));
const GIVERS=folk('r',5,[-2,-40.6,4,-39.6],0,{robe:0x5a2a4a, sash:0xb08d3c});   /* the rich putting in much */
const PLOTTERS=[{id:'kg1', name:'A chief kohen', dress:'kohen', at:[-6,-51.6], face:Math.PI, beard:0x6d6a66, kind:'oldman'},
                {id:'kg2', dress:'kohen', at:[-4.6,-52], face:Math.PI, beard:0x2c241f}];
const BAND=folk('b',10,[51,-62,57,-54],Math.PI/2);                               /* the crowd with swords and clubs */
const HPCOURT=folk('h',7,[10,30.6,16,34],0);                                     /* the officers about the fire */
const COUNCIL=folk('o',10,[5.6,24.8,18.4,25.4],0,{dress:'scribe', kind:'oldman'});
const YAHUDIM=folk('y',20,[-36,-56,-22,-51],Math.PI);                            /* before the Pavement */
const ROADFOLK=folk('f',12,[-62,-2,-54,8],Math.PI);                         /* following to the place of a skull */

STORY.act({
  id:'passion', n:7, num:'VI', title:'Passion Week',
  sub:'The entry · Pesach · Gethsemane · Golgotha',
  cast:{
    yahusha:Object.assign({},YAHUSHA),
    taught:{name:'The taught ones', kind:'crowd', actor:'andri', actors:TWELVE},
    crowds:{name:'The crowds', key:'the crowds', kind:'crowd', actor:'g2', actors:ids(GATECROWD)},
    city:{name:'All the city', key:'all the city', kind:'crowd', actor:'g5', actors:ids(GATECROWD)},
    children:{name:'The children', key:'the children', kind:'boy', actor:'kid0', actors:ids(KIDS)},
    kohanim:{name:'The chief kohanim and scribes', key:'chief kohanim and scribes', kind:'oldman', actor:'kg1', actors:['kg1','kg2']},
    herodians:{name:'The Pharisees and the Herodians', key:'the pharisees', kind:'man', actor:'ph1', actors:['ph1','hd1']},
    some:{name:'Some who were displeased', key:'some who were displeased', kind:'man', actor:'yahudahQ', actors:['yahudahQ','toma']},
    two:{name:'Kĕpha and Yahuchanon', key:'two who were sent', kind:'man', actor:'kepha', actors:['kepha','yahuchanon']},
    officers:{name:'The officers', key:'the officers', kind:'crowd', actor:'b1', actors:ids(BAND)},
    witnesses:{name:'Some who bore false witness', key:'false witnesses', kind:'man', actor:'o3', actors:['o3','o6']},
    mockers:{name:'Some of them', key:'those who struck Him', kind:'man', actor:'h2', actors:ids(HPCOURT)},
    girl:{name:'A servant girl', key:'the servant girl of the kohen gadol', kind:'woman', actor:'maid'},
    bystanders:{name:'Those who stood by', key:'those who stood by the fire', kind:'man', actor:'h1', actors:ids(HPCOURT)},
    another:{name:'Another', key:'another at the fire', kind:'man', actor:'h4'},
    yahudim:{name:'The Yahuḏim', key:'the yahudim', kind:'crowd', actor:'y2', actors:ids(YAHUDIM)},
    priests:{name:'The chief kohanim', key:'the chief kohanim', kind:'oldman', actor:'kg1', actors:['kg1','kg2']},
    wife:{name:'The wife of Pilate', key:'the wife of pilate', kind:'woman'},
    pilate:{name:'Pilate', key:'Pilate', kind:'man', folk:'roman'},
    people:{name:'All the people', key:'all the people', kind:'crowd', actor:'y4', actors:ids(YAHUDIM)},
    soldiers:{name:'The soldiers', key:'the soldiers', kind:'man', actor:'sold1', actors:['sold1','sold2','sold3','sold4']},
    psalmist:{name:'The Scripture', key:'the nabi', kind:'oldman'},
    rulers:{name:'The rulers', key:'the rulers', kind:'oldman', actor:'kg1', actors:['kg1','kg2']},
    standers:{name:'Some of those standing by', key:'those standing by the stake', kind:'crowd', actor:'f2', actors:ids(ROADFOLK)},
    someone:{name:'Someone', key:'someone with the sponge', kind:'man', actor:'f5'},
    seekers:{name:'The chief kohanim and Pharisees', key:'chief kohanim and pharisees', kind:'oldman', actor:'kg1', actors:['kg1','kg2']}
  },
  scenes:[

  /* ---------------- VI.1 — THE ENTRY ---------------- */
  { id:'entry', title:'Yahrushalayim', date:'before the Pesach, c. 30 CE', place:'yahrushalayim', time:'day',
    player:{ at:[-9,47], face:Math.PI, look:ADULT },
    crowds:[ {id:'pilgrims', n:320, area:[-42,28,8,76], path:[[-30,66],[-24,58],[-15.6,47],'gateIn',[-2,24]], clear:2.6, facePath:true} ],
    actors:[
      Object.assign({id:'yahusha', at:[-24,58], face:Math.PI*0.85},YAHUSHA),
      T('kepha',[-22,60],{face:Math.PI*0.85}), T('yahuchanon',[-26,60.6],{face:Math.PI*0.85}), T('andri',[-23.4,62.4],{face:Math.PI*0.85}),
      T('yaaqob',[-25.6,63],{face:Math.PI*0.85}), T('philip',[-21.4,63.6],{face:Math.PI*0.85}),
      ...GATECROWD
    ],
    things:[ {id:'colt', kind:'donkey', at:[-24,58]},
             {id:'branchCut', kind:'box', at:[-6.4,49.6], w:0.3, h:0.9, d:0.3, color:0x6d8a3e},
             {id:'branch', kind:'box', at:[-12.4,46], w:0.5, h:0.06, d:1.8, color:0x5e7a3a, hidden:true} ]
      .concat([0,1,2,3,4].map(k=>({id:'gar'+k, kind:'box', at:[-13.4+(k%2)*1.6,49-k*1.6], w:1, h:0.06, d:1.4, color:[0x7c6a52,0x5a6470,0x8e6f4c,0x6e5a70,0x7a5040][k], hidden:true}))),
    beats:[
      {t:'ride', who:'yahusha', on:'colt'},
      {t:'cam', from:[-2,9,58], look:[-14,4,36], dur:0.1},
      {t:'title', text:'Act VI · Passion Week', sub:'The entry · Pesach · Gethsemane · Golgotha'},
      {t:'note', text:'Pilgrims came up to Yahrushalayim from all the land for the Pesach, and the city was full. The road from the Mount of Olives brought Him round to her gates, and the crowds came out to meet Him.'},
      {t:'show', id:['gar0','gar1','gar2','gar3','gar4']},
      {t:'move', who:'yahusha', to:[-15.6,47], speed:0.8, wait:false},
      {t:'follow', who:['kepha','yahuchanon','andri','yaaqob','philip'], target:'yahusha'},
      {t:'read', ref:'MATTITHYAHU 21:8'},
      {t:'witness', text:'Cut a branch and spread it on the way', items:['branchCut'], verb:'Cut a branch', hold:0.8, deliver:[-12.4,46], r:2.2, carryText:'Lay it on the road before Him'},
      {t:'show', id:'branch'},
      {t:'face', who:'yahusha', to:'gateIn'},
      {t:'cam', on:'yahusha', shot:'back', toward:'g3', back:6, dur:2.5},
      {t:'say', who:'crowds', ref:'MATTITHYAHU 21:9', turn:false},
      {t:'move', who:'yahusha', to:'gateIn', speed:0.8},
      {t:'move', who:'yahusha', to:[-2,24], speed:0.8, wait:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'g3', back:6, dur:3},
      {t:'say', who:'city', ref:'MATTITHYAHU 21:10', turn:false},
      {t:'say', who:'crowds', ref:'MATTITHYAHU 21:11', turn:false},
      {t:'time', to:'dusk'},
      {t:'cam', from:[-12,12,6], look:[6,10,-44], dur:4},
      {t:'read', ref:'MARK 11:11'},
      {t:'cam', release:true},
      {t:'choice', prompt:'You', options:[
        {text:'Look up at the House', reply:'White and gold in the last of the sun, higher than anything men have built in the land. He looked round at all of it, and went out again.'},
        {text:'Watch the crowd', reply:'They are still singing at the gate. Half of them could not tell you who He is; the other half think they know.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.2 — THE HOUSE OF PRAYER ---------------- */
  { id:'cleansing', title:'The courts of the House', date:'the next day', place:'courts', time:'day',
    player:{ at:[-11,-38], face:Math.PI, look:ADULT },
    crowds:[ {id:'courtcrowd', n:240, area:[-42,-66,12,-34], look:[-22,-54], path:[[-11,-42.6],[-24,-55]], clear:2.2, keep:[[-35,-57.4,-14,-52.6]]} ],
    actors:[
      Object.assign({id:'yahusha', at:[-11,-42.6], face:Math.PI},YAHUSHA),
      T('kepha',[-9.6,-40.4],{face:Math.PI}), T('yahuchanon',[-12.4,-40.4],{face:Math.PI}), T('andri',[-10.4,-39.2],{face:Math.PI}),
      {id:'blind', name:'A blind man', at:[-16,-52], face:-Math.PI/2, robe:0x6b5a44, cloth:0x8a7a60, beard:0x6d6a66, kind:'oldman', hidden:true},
      {id:'lame', name:'A lame man', at:[-15,-53.4], face:-Math.PI/2, robe:0x5c5040, cloth:0xa89a7e, beard:0x2c241f, sit:true, hidden:true},
      ...SELLERS, ...COURTFOLK, ...PLOTTERS.map(a=>Object.assign({},a,{hidden:true})), ...KIDS.map(a=>Object.assign({},a,{hidden:true}))
    ],
    things:[0,1,2,3].map(k=>({id:'tbl'+k, kind:'box', at:[-32+k*5,-55], w:2, h:0.8, d:0.9, color:0x6e5238}))
      .concat([0,1,2,3].map(k=>({id:'tip'+k, kind:'box', at:[-31.6+k*5,-54.2], w:2, h:0.3, d:0.9, face:0.3+k*0.4, color:0x6e5238, hidden:true})))
      .concat([0,1,2,3,4,5].map(k=>({id:'coin'+k, kind:'box', at:[-31+k*3.1,-53.4+(k%2)*0.8], w:0.12, h:0.03, d:0.12, color:0xc8a050, hidden:true})))
      .concat([0,1].map(k=>({id:'dove'+k, kind:'dove', at:[-32+k*3.4,-50], y:5, hidden:true}))),
    beats:[
      {t:'cam', from:[-2,8,-32], look:[-24,3,-56], dur:0.1},
      {t:'note', text:'In the great court of the House — the court any nation might enter — the money changers sat at their tables, changing the coins of every land into the silver of the House, and the sellers sat with doves and beasts for the offerings.'},
      {t:'move', who:['yahusha','kepha','yahuchanon','andri'], to:[[-24,-52.6],[-22,-50.6],[-25.6,-50.4],[-23.4,-49.4]], speed:1.2, wait:false},
      {t:'goal', text:'Go up the steps into the court with them', goto:'outer', r:5},
      {t:'face', who:'yahusha', to:'tbl1'},
      {t:'cam', on:'yahusha', shot:'back', toward:'v2', dur:1.6},
      {t:'hide', id:['tbl0','tbl1','tbl2','tbl3']},
      {t:'show', id:['tip0','tip1','tip2','tip3','coin0','coin1','coin2','coin3','coin4','coin5','dove0','dove1']},
      {t:'drift', id:['dove0','dove1'], by:[6,8,-10], dur:4, wait:false},
      {t:'move', who:ids(SELLERS), to:SELLERS.map((a,k)=>[-38+k*0.8,-70+k*0.6]), speed:2.6, wait:false},
      {t:'read', ref:'MARK 11:15'},
      {t:'read', ref:'MARK 11:16'},
      {t:'cam', on:'yahusha', shot:'back', toward:'c3', dur:1.8},
      {t:'say', who:'yahusha', ref:'MARK 11:17', turn:false},
      {t:'show', id:['blind','lame']},
      {t:'move', who:['blind','lame'], to:[[-22.4,-50.4],[-23.4,-50.8]], speed:1},
      {t:'face', who:'yahusha', to:'blind'},
      {t:'cam', from:[-19,5.6,-55.4], look:[-22.8,4.4,-51], dur:2},
      {t:'read', ref:'MATTITHYAHU 21:14'},
      {t:'stand', who:'lame'},
      {t:'move', who:'lame', to:[-19.6,-51.6], speed:1.6, wait:false},
      {t:'show', id:ids(KIDS).concat(['kg1','kg2'])},
      {t:'move', who:ids(KIDS), to:[[-19.6,-50.2],[-20.6,-50.4],[-21.4,-51.4],[-20.2,-51.8]], speed:1.6},
      {t:'cam', from:[-17.4,5.4,-54.6], look:'kid1', dur:2},
      {t:'say', who:'children', ref:'MATTITHYAHU 21:15', turn:false},
      {t:'move', who:['kg1','kg2'], to:[[-21,-51.4],[-22.6,-51.2]], speed:1.4},
      {t:'face', who:'yahusha', to:'kg1'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kg1', dur:1.6},
      {t:'say', voices:['kohanim','yahusha'], ref:'MATTITHYAHU 21:16', turn:false},
      {t:'cam', release:true},
      {t:'read', ref:'MARK 11:18'},
      {t:'choice', prompt:'You', options:[
        {text:'Pick up a fallen coin', reply:'A silver piece of Tsor, with a god on it. It is the only coin the House will take. You set it on the step.'},
        {text:'Watch the children', reply:'They have no idea they are quoting a psalm. They are just shouting what everyone shouted at the gate.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.3 — CAESAR'S COIN, AND THE WIDOW'S TWO COINS ---------------- */
  { id:'treasury', title:'The courts of the House', date:'in the days before the Pesach', place:'courts', time:'day',
    player:{ at:[6,-31], face:Math.PI, look:ADULT },
    crowds:[ {id:'courtcrowd', n:160, area:[-30,-60,22,-32], look:'treasury', keep:[[-6,-41.4,18,-36.6]]} ],
    actors:[
      Object.assign({id:'yahusha', at:[8.6,-38.6], face:-Math.PI/2},YAHUSHA),
      T('kepha',[10.4,-38],{face:-Math.PI/2}), T('yahuchanon',[10.6,-39.6],{face:-Math.PI/2}), T('andri',[12,-38.8],{face:-Math.PI/2}),
      {id:'ph1', name:'A Pharisee', dress:'scribe', at:[3.8,-38.4], face:Math.PI/2, robe:0xe6e0cf, cloth:0x5a4a3a, beard:0x6d6a66, kind:'oldman'},
      {id:'hd1', name:'One of the Herodians', dress:'herodian', at:[4,-39.8], face:Math.PI/2, robe:0x6a2a4a, cloth:0xe6dcc0, beard:0x2c241f},
      {id:'widow', name:'A poor widow', kind:'woman', at:[-6,-39.4], face:Math.PI/2, robe:0x3c3a44, cloth:0x2e2a30, skin:0x7a4e30, hidden:true},
      ...GIVERS.map(a=>Object.assign({},a,{hidden:true}))
    ],
    things:[ {id:'denar', kind:'box', at:[5.6,-39], w:0.1, h:0.02, d:0.1, color:0xd8d8d0, y:5.4, hidden:true} ],
    beats:[
      {t:'cam', from:[14,7,-30], look:[6,4.6,-40], dur:0.1},
      {t:'read', ref:'MARK 12:13'},
      {t:'goal', text:'Go up into the court of the women, where He is teaching', goto:'womenCourt', r:4},
      {t:'cam', from:[6,6.2,-35.6], look:'ph1', dur:2},
      {t:'say', who:'herodians', ref:'MARK 12:14', turn:false},
      {t:'face', who:'yahusha', to:'ph1'},
      {t:'cam', on:'yahusha', shot:'back', toward:'ph1', dur:1.6},
      {t:'say', voices:['herodians','yahusha'], ref:'MARK 12:15', turn:false},
      {t:'show', id:'denar'},
      {t:'cam', on:'yahusha', shot:'body', dur:1.6},
      {t:'say', voices:['yahusha','herodians'], ref:'MARK 12:16', turn:false},
      {t:'hide', id:'denar'},
      {t:'cam', on:'yahusha', shot:'back', toward:'ph1', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 12:17', turn:false},
      {t:'move', who:['ph1','hd1'], to:[[0,-34],[1,-33]], speed:1.2, wait:false},
      {t:'move', who:'yahusha', to:'treasurySeat', speed:1},
      {t:'face', who:'yahusha', to:'treasury'},
      {t:'sit', who:'yahusha'},
      {t:'show', id:ids(GIVERS)},
      {t:'cam', on:'yahusha', shot:'back', toward:'r1', dur:2},
      {t:'read', ref:'MARK 12:41'},
      {t:'show', id:'widow'},
      {t:'move', who:'widow', to:[-1.6,-38.4], speed:0.7},
      {t:'cam', from:[3.4,5.8,-35.6], look:'widow', dur:2},
      {t:'read', ref:'MARK 12:42'},
      {t:'move', who:'widow', to:[-8,-37], speed:0.7, wait:false},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 12:43-44', turn:false},
      {t:'cam', release:true},
      {t:'choice', prompt:'You', options:[
        {text:'Watch the widow go', reply:'Two copper coins. Nobody else in the court saw her. He did.'},
        {text:'Think of the coin with Caesar’s face', reply:'Give Caesar his own coin back. And give Aluahim what has His likeness on it.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.4 — THE ANOINTING AT BĔYTH ANYAH ---------------- */
  { id:'anointing', title:'Bĕyth Anyah', date:'two days before the Pesach', place:'bethanyah', time:'dusk',
    player:{ at:[8,-2], face:-Math.PI*0.75, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:[-2.2,2.4], face:Math.PI/2, sit:true},YAHUSHA),
      T('kepha',[0,1.2],{face:0, sit:true}), T('yahuchanon',[-1,1.2],{face:0, sit:true}), T('andri',[1,1.2],{face:0, sit:true}),
      T('yahudahQ',[0.4,3.6],{face:Math.PI, sit:true}), T('toma',[-0.8,3.6],{face:Math.PI, sit:true}), T('philip',[1.6,3.6],{face:Math.PI, sit:true}),
      {id:'shimonL', name:'Shim‛on the leper', at:[2.8,2.4], face:-Math.PI/2, sit:true, robe:0x8a7a60, cloth:0xe6e0cf, beard:0x6d6a66, kind:'oldman'},
      {id:'woman', name:'A woman', kind:'woman', at:'houseDoor', face:Math.PI/2, robe:0x5a4a6a, cloth:0x3c3a44, skin:0x7a4e30},
      {id:'kg1', name:'A chief kohen', dress:'kohen', at:[26,-6], face:-Math.PI/2, beard:0x6d6a66, kind:'oldman', hidden:true}
    ],
    things:[ {id:'table', kind:'box', at:[0.2,2.4], w:3, h:0.4, d:1, color:0x6e5238},
             {id:'flask', kind:'box', at:'houseDoor', w:0.12, h:0.22, d:0.12, y:1.05, color:0xf0ece0} ],
    beats:[
      {t:'cam', from:[9,3,-1], look:[0,0.8,2.4], dur:0.1},
      {t:'read', ref:'MARK 14:1'},
      {t:'say', who:'kohanim', ref:'MARK 14:2'},
      {t:'goal', text:'Come in to the house of Shim‛on, where they are at the table', goto:[5.4,0.6], r:2.6},
      {t:'move', who:'woman', to:[-3.4,2.4], speed:0.9},
      {t:'hide', id:'flask'},
      {t:'cam', from:[-1.6,1.9,-1.2], look:[-2.6,1.1,2.4], dur:2},
      {t:'read', ref:'MARK 14:3'},
      {t:'cam', from:[3.8,1.5,0.4], look:'yahudahQ', dur:1.8},
      {t:'say', who:'some', ref:'MARK 14:4'},
      {t:'say', who:'some', ref:'MARK 14:5'},
      {t:'cam', on:'yahusha', shot:'back', toward:'yahudahQ', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:6', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:7', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:8', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:9', turn:false},
      {t:'stand', who:'yahudahQ'},
      {t:'move', who:'yahudahQ', to:[14,-4], speed:1.3, wait:false},
      {t:'cam', from:[4,2.2,4.6], look:[18,1.2,-5], dur:3},
      {t:'read', ref:'MARK 14:10'},
      {t:'show', id:'kg1'},
      {t:'move', who:'yahudahQ', to:[24,-6.4], speed:1.3},
      {t:'face', who:'yahudahQ', to:'kg1'},
      {t:'read', ref:'MARK 14:11'},
      {t:'cam', release:true},
      {t:'choice', prompt:'You', options:[
        {text:'Breathe in the nard', reply:'The whole house is full of it. Three hundred pieces of silver, poured out in a moment.'},
        {text:'Look down the road after Yahuḏah', reply:'He keeps the bag. You never thought twice about him. You do now.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.5 — THE PESACH MADE READY ---------------- */
  { id:'prepare', title:'Yahrushalayim', date:'the Day of Unleavened Bread', place:'upperroom', time:'day',
    player:{ at:[-10,44], face:Math.PI, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:[-14,48], face:0},YAHUSHA),
      T('kepha',[-12.6,46.2],{face:Math.PI}), T('yahuchanon',[-15.4,46.4],{face:Math.PI}),
      {id:'jarman', name:'A man carrying a jar of water', at:[-2,30], face:Math.PI, robe:0x8a7a60, cloth:0xcfc4aa, beard:0x3a2a1e, carrying:true},
      {id:'master', name:'The master of the house', at:[17,24], face:Math.PI, robe:0x5f6a52, cloth:0xe6e0cf, beard:0x6d6a66, kind:'oldman'}
    ],
    things:[ {id:'basin', kind:'jar', at:[21.4,24.6]} ],
    beats:[
      {t:'cam', from:[-4,5,52], look:[-14,1.6,46], dur:0.1},
      {t:'read', ref:'LUKE 22:7'},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'LUKE 22:8', turn:false},
      {t:'say', who:'two', ref:'LUKE 22:9', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 22:10', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 22:11', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 22:12', turn:false},
      {t:'cam', release:true},
      {t:'move', who:['kepha','yahuchanon'], to:['gateIn',['gateIn',-1.4,0.6]], speed:1.4},
      {t:'move', who:'jarman', to:[-6,30], speed:1, wait:false},
      {t:'move', who:['kepha','yahuchanon'], to:[[-6.4,32],[-7.6,32.6]], speed:1.3},
      {t:'goal', text:'Go in with them, and follow the man with the jar', goto:[-8,34], r:4},
      {t:'move', who:'jarman', to:[16,24.6], speed:1},
      {t:'move', who:['kepha','yahuchanon'], to:[[15.4,23.4],[14,23]], speed:1.1},
      {t:'face', who:'master', to:'kepha'},
      {t:'cam', from:[11,2,20], look:[16.6,1.4,24], dur:2},
      {t:'read', ref:'LUKE 22:13'},
      {t:'witness', text:'Carry the basin and the water up to the room', items:['basin'], verb:'Lift the basin', hold:0.5, deliver:'roomIn', r:2, carryText:'Up the stair at the side of the house, into the upper room'},
      {t:'choice', prompt:'You', options:[
        {text:'Look round the room', reply:'Cushions about a low table, lamps in the walls, the unleavened bread laid ready. Large enough for thirteen and a few more.'},
        {text:'Think of His words at the gate', reply:'A man carrying a jar of water — women carry the water. He was there, just as He said.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.6 — THE SUPPER ---------------- */
  { id:'supper', title:'The upper room', date:'the night of the Pesach', place:'upperroom', time:'night',
    player:{ at:[21,33], face:-Math.PI*0.75, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:[16.8,28.7], face:0, sit:true},YAHUSHA),
      T('andri',[14.4,28.7],{face:0, sit:true}), T('yahuchanon',[15.6,28.7],{face:0, sit:true}), T('yahudahQ',[18,28.7],{face:0, sit:true}),
      T('philip',[19.2,28.7],{face:0, sit:true}),
      T('kepha',[14.6,31.3],{face:Math.PI, sit:true}), T('yaaqob',[15.8,31.3],{face:Math.PI, sit:true}), T('mattithyahu',[17,31.3],{face:Math.PI, sit:true}),
      T('toma',[18.2,31.3],{face:Math.PI, sit:true}), T('bartholomi',[19.4,31.3],{face:Math.PI, sit:true}),
      T('yaaqobA',[13.6,30],{face:Math.PI/2, sit:true}), T('shimonZ',[20.4,29.4],{face:-Math.PI/2, sit:true}), T('yahudahY',[20.4,30.6],{face:-Math.PI/2, sit:true})
    ],
    things:[ {id:'basinS', kind:'jar', at:[13,32.6]} ],
    beats:[
      {t:'cam', from:[13,4.6,26.9], look:[18,3,31], dur:0.1},
      {t:'read', ref:'YAHUCHANON 13:1'},
      {t:'read', ref:'YAHUCHANON 13:2-4'},
      {t:'stand', who:'yahusha'},
      {t:'move', who:'yahusha', to:[13.4,32.2], speed:0.8},
      {t:'read', ref:'YAHUCHANON 13:5'},
      {t:'move', who:'yahusha', to:[14.6,32.5], speed:0.8},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', from:[13.2,4.6,33.6], look:[14.6,3.2,31.3], dur:1.8},
      {t:'say', who:'kepha', ref:'YAHUCHANON 13:6', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.4},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:7', turn:false},
      {t:'say', voices:['kepha','yahusha'], ref:'YAHUCHANON 13:8', turn:false},
      {t:'say', who:'kepha', ref:'YAHUCHANON 13:9', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:10', turn:false},
      {t:'read', ref:'YAHUCHANON 13:11', voices:['yahusha']},
      {t:'move', who:'yahusha', to:[16.8,28.7], speed:0.8},
      {t:'face', who:'yahusha', to:[16.8,32]},
      {t:'sit', who:'yahusha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'philip', dur:2},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:12', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:13', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:14', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:15', turn:false},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:21', turn:false},
      {t:'cam', from:[21,4.4,26.8], look:[16,3,30.4], dur:2},
      {t:'say', who:'taught', ref:'MATTITHYAHU 26:22', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'yahudahQ', dur:1.6},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:23', turn:false},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:24', turn:false},
      {t:'say', voices:['yahudahQ','yahusha'], ref:'MATTITHYAHU 26:25', turn:false},
      {t:'cam', from:[15.6,4.4,26.9], look:[14.2,3.2,29.2], dur:1.8},
      {t:'read', ref:'YAHUCHANON 13:23'},
      {t:'read', ref:'YAHUCHANON 13:24'},
      {t:'say', who:'yahuchanon', ref:'YAHUCHANON 13:25', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'yahudahQ', dur:1.6},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:26', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:27', turn:false},
      {t:'read', ref:'YAHUCHANON 13:28'},
      {t:'read', ref:'YAHUCHANON 13:29', voices:['yahusha']},
      {t:'stand', who:'yahudahQ'},
      {t:'move', who:'yahudahQ', to:'roomDoor', speed:1.4},
      {t:'cam', from:[18.6,4.6,27], look:[22.4,3.6,30], dur:1.6},
      {t:'move', who:'yahudahQ', to:'stairTop', speed:1.4, wait:false},
      {t:'read', ref:'YAHUCHANON 13:30'},
      {t:'hide', id:'yahudahQ'},
      {t:'cam', on:'yahusha', shot:'body', dur:2},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:26', turn:false},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:27-28', turn:false},
      {t:'say', who:'yahusha', ref:'MATTITHYAHU 26:29', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'philip', dur:2},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 13:34-35', turn:false},
      {t:'stand', who:['yahusha'].concat(TWELVE.filter(k=>k!=='yahudahQ'))},
      {t:'cam', from:[13,4.6,26.9], look:[20,3.4,31], dur:2},
      {t:'read', ref:'MATTITHYAHU 26:30'},
      {t:'choice', prompt:'You', options:[
        {text:'Think of the basin you carried up', reply:'You carried it up for the guests to wash. You did not think He would be the one to kneel with it.'},
        {text:'Think of the door Yahuḏah went out by', reply:'You held it open for him. It was night.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.7 — GETHSEMANE ---------------- */
  { id:'gethsemane', title:'Gethsemane', date:'that night', place:'olivet', time:'lamplit',
    player:{ at:[51.4,-60.4], face:Math.PI/2, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:[56,-57.6], face:Math.PI/2},YAHUSHA),
      T('kepha',[54.6,-56.2],{face:Math.PI/2}), T('yaaqob',[53.4,-56.8],{face:Math.PI/2}), T('yahuchanon',[53.6,-58.8],{face:Math.PI/2}),
      T('andri',[52.4,-57.6],{face:Math.PI/2}), T('philip',[51.6,-56.2],{face:Math.PI/2}), T('toma',[51.4,-58.8],{face:Math.PI/2}),
      T('mattithyahu',[50.4,-57.4],{face:Math.PI/2}), T('bartholomi',[50.2,-55.8],{face:Math.PI/2})
    ],
    things:[ {id:'lamp', kind:'jar', at:[60.4,-56.6]} ],
    glows:[ {id:'lampGlow', at:[61,1.6,-57], size:1.6, color:0xffb060, intensity:1, hidden:true},
            {id:'malak', at:[78.6,-62.4], dy:3.4, size:3, color:0xfff4d8, intensity:1.1, hidden:true} ],
    beats:[
      {t:'cam', from:['qidron',-2,6], fdy:3.4, look:'yahusha', dur:0.1},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:27-28', turn:false},
      {t:'say', who:'kepha', ref:'MARK 14:29', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:30', turn:false},
      {t:'say', who:'kepha', ref:'MARK 14:31', turn:false},
      {t:'cam', release:true},
      {t:'move', who:['yahusha','kepha','yaaqob','yahuchanon','andri','philip','toma','mattithyahu','bartholomi'],
        to:['gIn',[63.6,-56.4],[63.2,-59.4],[64.4,-60],[65.6,-55.4],[66.6,-56],[64.6,-54.8],[66.8,-54.4],[63.6,-54.6]], speed:1.1, wait:false},
      {t:'read', ref:'YAHUCHANON 18:1'},
      {t:'witness', text:'Light the lamp at the gate of the garden for those who wait', items:['lamp'], verb:'Light the lamp', hold:0.8, reach:2.2, reveal:{lamp:'lampGlow'}},
      {t:'move', who:['andri','philip','toma','mattithyahu','bartholomi'], to:[[65.4,-55.6],[66.6,-56.4],[64.6,-54.8],[66.8,-54.4],[63.6,-54.6]], speed:1, wait:false},
      {t:'face', who:'yahusha', to:'andri'},
      {t:'cam', on:'yahusha', shot:'back', toward:'andri', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:32', turn:false},
      {t:'sit', who:['andri','philip','toma','mattithyahu','bartholomi']},
      {t:'move', who:['yahusha','kepha','yaaqob','yahuchanon'], to:[[70.4,-58.2],[69.4,-56.6],[69,-59.6],[70.2,-60.4]], speed:0.9},
      {t:'read', ref:'MARK 14:33'},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:34', turn:false},
      {t:'move', who:'yahusha', to:'prayer', speed:0.8},
      {t:'face', who:'yahusha', to:[80,-58.6]},
      {t:'lie', who:'yahusha', prone:true},
      {t:'cam', from:[71,5.4,-57], look:[75.4,6.2,-58.6], dur:2.5},          /* low behind Him, fallen on His face, under the olives */
      {t:'read', ref:'MARK 14:35'},
      {t:'say', who:'yahusha', ref:'MARK 14:36', turn:false},
      {t:'show', id:'malak'},
      {t:'drift', id:'malak', to:[76.3,5.7,-59.2], dur:3.5, wait:false},     /* "a mal'ak … appeared to Him, strengthening Him": the light comes down to Him */
      {t:'read', ref:'LUKE 22:43'},
      {t:'read', ref:'LUKE 22:44'},
      {t:'hide', id:'malak'},
      {t:'sit', who:['kepha','yaaqob','yahuchanon']},
      {t:'lie', who:['kepha','yahuchanon']},
      {t:'stand', who:'yahusha'}, {t:'place', who:'yahusha', at:'prayer', y:null},
      {t:'move', who:'yahusha', to:[71.6,-58.4], speed:0.9},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:37', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:38', turn:false},
      {t:'move', who:'yahusha', to:'prayer', speed:0.8},
      {t:'cam', from:[66,3,-62], look:[74.6,0.8,-58.6], dur:2.5},
      {t:'read', ref:'MARK 14:39'},
      {t:'move', who:'yahusha', to:[71.6,-58.4], speed:0.9},
      {t:'read', ref:'MARK 14:40'},
      {t:'stand', who:['kepha','yaaqob','yahuchanon']},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.6},
      {t:'say', who:'yahusha', ref:'MARK 14:41-42', turn:false},
      {t:'end'}
    ]},

  /* ---------------- VI.8 — THE ARREST ---------------- */
  { id:'arrest', title:'Gethsemane', date:'that night', place:'olivet', time:'lamplit',
    player:{ at:[64.6,-61], face:-Math.PI/2, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:[68,-58.2], face:-Math.PI/2},YAHUSHA),
      T('kepha',[68.6,-56.4],{face:-Math.PI/2}), T('yaaqob',[69.4,-59.8],{face:-Math.PI/2}), T('yahuchanon',[69.6,-57.4],{face:-Math.PI/2}),
      T('andri',[66,-55.2],{face:-Math.PI/2}), T('philip',[66.6,-60.8],{face:-Math.PI/2}), T('toma',[67.4,-61.6],{face:-Math.PI/2}),
      T('yahudahQ',[50,-58],{face:Math.PI/2}),
      {id:'melek', name:'Meleḵ', at:[51,-60], face:Math.PI/2, robe:0x6a5a44, cloth:0x8a7a60, beard:0x2c241f},
      ...BAND
    ],
    glows:[0,1,2,3,4].map(k=>({id:'torch'+k, at:[52+k*1.2,2.2,-62+k*2.2], size:1.4, color:0xff9a40, intensity:0.9}))
      /* "and having touched his ear, He healed him" (Luke 22:51) */
      .concat([{id:'ear', at:[62.6,-60], dy:1.7, size:0.8, color:0xfff4d8, intensity:0.5, hidden:true}]),
    beats:[
      {t:'cam', from:['three',2,-4], fdy:2.4, look:'yahudahQ', dur:0.1},
      {t:'move', who:['yahudahQ','melek'].concat(ids(BAND)), to:[[63.4,-58],[62.6,-60]].concat(BAND.map((a,k)=>[58.6+(k%5)*1.1,-61+Math.floor(k/5)*3.4+(k%2)*0.6])), speed:1.4, wait:false},
      {t:'drift', id:['torch0','torch1','torch2','torch3','torch4'], by:[7,0,1], dur:6, wait:false},
      {t:'read', ref:'MARK 14:43'},
      {t:'read', ref:'MARK 14:44', voices:['yahudahQ']},
      {t:'move', who:'yahusha', to:[65.4,-58.2], speed:0.9},
      {t:'cam', on:'yahusha', shot:'back', toward:'b2', dur:1.8},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 18:4', turn:false},
      {t:'say', voices:['officers','yahusha'], ref:'YAHUCHANON 18:5', turn:false},
      {t:'lie', who:ids(BAND).slice(0,6)},
      {t:'read', ref:'YAHUCHANON 18:6', voices:['yahusha']},
      {t:'stand', who:ids(BAND).slice(0,6)},
      {t:'say', voices:['yahusha','officers'], ref:'YAHUCHANON 18:7', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 18:8', turn:false},
      {t:'read', ref:'YAHUCHANON 18:9', voices:['yahusha']},
      {t:'move', who:'yahudahQ', to:[64.6,-58.2], speed:1},
      {t:'cam', from:[61.8,1.9,-55.6], look:[65,1.4,-58.2], dur:1.6},
      {t:'say', who:'yahudahQ', ref:'MARK 14:45', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'yahudahQ', dur:1.4},
      {t:'say', who:'yahusha', ref:'LUKE 22:48', turn:false},
      {t:'say', who:'taught', ref:'LUKE 22:49', turn:false},
      {t:'move', who:'kepha', to:[63.6,-59.4], speed:2.4},
      {t:'cam', from:[66.6,2,-62.6], look:[63,1.3,-60], dur:1.4},
      {t:'read', ref:'YAHUCHANON 18:10'},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', dur:1.4},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 18:11', turn:false},
      {t:'move', who:'kepha', to:[64.6,-61.4], speed:1.2, wait:false},
      {t:'move', who:'yahusha', to:[63.8,-59], speed:1},
      {t:'face', who:'yahusha', to:'melek'}, {t:'face', who:'melek', to:'yahusha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'melek', back:2.2, dur:1.4},
      {t:'show', id:'ear'},
      {t:'say', who:'yahusha', ref:'LUKE 22:51', turn:false},
      {t:'hide', id:'ear'},
      {t:'face', who:'yahusha', to:'b2'},
      {t:'cam', on:'yahusha', shot:'back', toward:'b2', dur:1.4},
      {t:'say', who:'yahusha', ref:'MARK 14:48-49', turn:false},
      {t:'move', who:['kepha','yaaqob','yahuchanon','andri','philip','toma'], to:[[88,-72],[90,-50],[92,-60],[86,-44],[94,-70],[96,-56]], speed:3.4, wait:false},
      {t:'cam', from:['qidron',2,-6], fdy:3.4, look:'yahusha', dur:2},
      {t:'read', ref:'MARK 14:50'},
      {t:'hide', id:['kepha','yaaqob','yahuchanon','andri','philip','toma']},
      {t:'move', who:['yahusha'].concat(ids(BAND).slice(0,4)), to:[[54,-58],[54.8,-56.6],[55,-59.6],[53.2,-57],[53.4,-59.2]], speed:1, wait:false},
      {t:'read', ref:'YAHUCHANON 18:12-13'},
      {t:'read', ref:'YAHUCHANON 18:14'},
      {t:'choice', prompt:'You', options:[
        {text:'Run with the others', reply:'You are halfway up the slope before you know you have run. The torches go down toward the city without you.'},
        {text:'Follow the torches at a distance', reply:'Kĕpha is ahead of you in the dark, keeping well back. So are you.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.9 — THE COURTYARD OF THE KOHEN GADOL ---------------- */
  { id:'courtyard', title:'The house of the kohen gadol', date:'that night', place:'highpriest', time:'lamplit',
    player:{ at:[15.4,33.6], face:-Math.PI*0.75, look:ADULT },
    actors:[
      Object.assign({id:'yahusha', at:'accused', face:Math.PI},YAHUSHA),
      {id:'qayapha', name:'Qayapha the kohen gadol', key:'Qayapha', dress:'kohen', at:'qayapha', face:0, robe:0x3a3a6a, cloth:0xe8e0cc, beard:0x6d6a66, kind:'oldman', sit:true, bench:true},
      T('kepha',[27,30],{face:-Math.PI/2}),
      {id:'maid', name:'A servant girl', kind:'woman', at:[20.2,31.4], face:Math.PI/2, robe:0x7a5a4a, cloth:0xe8e2d2, skin:0x7c5430},
      ...COUNCIL.map(a=>Object.assign({},a,{sit:true})), ...HPCOURT
    ],
    things:[ {id:'seatQ', kind:'throne', style:'kohen', at:'qayapha', face:0} ],
    beats:[
      {t:'cam', from:[20,4.4,35], look:[12,1.4,27], dur:0.1},
      {t:'read', ref:'MARK 14:53'},
      {t:'read', ref:'YAHUCHANON 18:15'},
      {t:'move', who:'kepha', to:[21.6,30], speed:1},
      {t:'read', ref:'YAHUCHANON 18:16'},
      {t:'move', who:'kepha', to:[14.2,33.8], speed:1},
      {t:'face', who:'kepha', to:'fire'},
      {t:'read', ref:'YAHUCHANON 18:18'},
      {t:'goal', text:'Stand at the fire with them; it is cold', goto:'fire', r:2.6},
      {t:'cam', from:[13,2.4,35.6], look:[12,1.6,26.4], dur:2.5},
      {t:'read', ref:'MARK 14:55'},
      {t:'read', ref:'MARK 14:56'},
      {t:'say', who:'witnesses', ref:'MARK 14:57-58', turn:false},
      {t:'read', ref:'MARK 14:59'},
      {t:'stand', who:'qayapha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'qayapha', dur:1.8},
      {t:'say', who:'qayapha', ref:'MARK 14:60', turn:false},
      {t:'say', who:'qayapha', ref:'MARK 14:61', turn:false},
      {t:'say', who:'yahusha', ref:'MARK 14:62', turn:false},
      {t:'say', who:'qayapha', ref:'MARK 14:63-64', turn:false},
      {t:'cam', from:[16,1.8,34.8], look:'kepha', dur:2},
      {t:'read', ref:'MARK 14:65', voices:['mockers']},
      {t:'move', who:'maid', to:[15.6,33], speed:0.9},
      {t:'face', who:'maid', to:'kepha'},
      {t:'say', who:'girl', ref:'MARK 14:66-67', turn:false},
      {t:'say', who:'kepha', ref:'MARK 14:68', turn:false},
      {t:'move', who:'kepha', to:[20.6,32.6], speed:1},
      {t:'say', who:'girl', ref:'MARK 14:69', turn:false},
      {t:'say', who:'bystanders', ref:'MARK 14:70', turn:false},
      {t:'say', who:'another', ref:'LUKE 22:59', turn:false},
      {t:'say', who:'kepha', ref:'LUKE 22:60', turn:false},
      {t:'face', who:'yahusha', to:'kepha'},
      {t:'cam', on:'yahusha', shot:'back', toward:'kepha', back:5, dur:2.4},
      {t:'read', ref:'LUKE 22:61', voices:['yahusha']},
      {t:'move', who:'kepha', to:'hpStreet', speed:1.2, wait:false},
      {t:'cam', from:[18,2.2,33.6], look:[24,1.3,30], dur:2},
      {t:'read', ref:'LUKE 22:62'},
      {t:'hide', id:'kepha'},
      {t:'time', to:'dawn'},
      {t:'choice', prompt:'You', options:[
        {text:'Go after Kĕpha', reply:'He is sitting against the wall in the lane with his face in his hands. You sit down beside him and say nothing.'},
        {text:'Stay by the fire', reply:'The servant girl looks at you too. You hold her eyes, and she looks away.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.10 — BEFORE PILATE ---------------- */
  { id:'pilate', title:'The Pavement', date:'early, the Preparation of the Pesach', place:'praetorium', time:'dawn',
    player:{ at:[-24,-52], face:Math.PI, look:ADULT },
    crowds:[ {id:'multitude', n:280, area:[-48,-58,-14,-40], look:'pavement', keep:[[-41,-64,-26,-58.4]], path:[[-32,-58],[-22,-51],[-11,-41]], clear:1.4} ],
    actors:[
      Object.assign({id:'yahusha', at:[-30,-55], face:Math.PI},YAHUSHA),
      {id:'pilate', name:'Pilate', key:'Pilate', folk:'roman', dress:'herodian', at:'palaceIn', face:0, robe:0xece6d6, cloth:0x8a2a22, sash:0xb08d3c, skin:0xb08060, bench:true},
      LEGION('sold1',[-31.2,-56],Math.PI), LEGION('sold2',[-28.8,-56],Math.PI),
      LEGION('sold3',[-34.4,-63.4],0), LEGION('sold4',[-29.6,-63.4],0),
      {id:'barabba', name:'Barabba', key:'Barabba', at:'palaceDoor', face:0, robe:0x4a3a2a, cloth:0x6a5a44, beard:0x1e1814, hidden:true},
      /* "the entire company of soldiers" gathered in the court (Mattithyahu 27:27) */
      ...[0,1,2,3,4,5].map(k=>{ const a=k/6*Math.PI*2+0.5; return LEGION('coh'+k,['palaceIn',Math.cos(a)*2.4,-1.4+Math.sin(a)*2.2],a+Math.PI/2*0,{hidden:true}); }),
      ...PLOTTERS.map((a,k)=>Object.assign({},a,{at:[-31.6+k*2.8,-52.6]})),
      ...YAHUDIM
    ],
    things:[ {id:'basinP', kind:'jar', at:'basin'},
             {id:'mishpat', kind:'throne', style:'roman', at:'throne', face:0},
             {id:'post', kind:'box', at:['palaceIn',0,-2.2], w:0.42, h:1.05, d:0.42, color:0x9a9080} ],
    beats:[
      {t:'cam', from:[-16,9,-44], look:[-32,4,-62], dur:0.1},
      {t:'move', who:['yahusha','sold1','sold2'], to:['palaceDoor',[-33.4,-62],[-30.6,-62]], speed:1},
      {t:'read', ref:'YAHUCHANON 18:28'},
      {t:'move', who:'pilate', to:'pavement', speed:1},
      {t:'face', who:'pilate', to:'kg1'},
      {t:'cam', from:[-27,5.4,-55.4], look:'pilate', dur:2},
      {t:'say', who:'pilate', ref:'YAHUCHANON 18:29', turn:false},
      {t:'say', who:'yahudim', ref:'YAHUCHANON 18:30', turn:false},
      {t:'say', voices:['pilate','yahudim'], ref:'YAHUCHANON 18:31-32', turn:false},
      {t:'move', who:['pilate','yahusha'], to:['palaceIn',[-32,-66.6]], speed:1},
      {t:'face', who:'pilate', to:'yahusha'}, {t:'face', who:'yahusha', to:'pilate'},
      {t:'cam', on:'yahusha', shot:'back', toward:'pilate', dur:1.8},
      {t:'say', who:'pilate', ref:'YAHUCHANON 18:33', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 18:34', turn:false},
      {t:'say', who:'pilate', ref:'YAHUCHANON 18:35', turn:false},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 18:36', turn:false},
      {t:'say', voices:['pilate','yahusha'], ref:'YAHUCHANON 18:37', turn:false},
      {t:'say', who:'pilate', ref:'YAHUCHANON 18:38', turn:false},
      {t:'move', who:'pilate', to:'pavement', speed:1.2},
      {t:'cam', from:[-27,5.4,-55.4], look:'pilate', dur:1.6},
      /* THE CHOICE (Mattithyahu 27:15-23; Mark 15:7; Yahuchanon 18:39-40): the prisoner the governor
         releases at the festival — Barabba, brought out in his chains, or Yahusha */
      {t:'read', ref:'MATTITHYAHU 27:15'},
      {t:'show', id:'barabba'},
      {t:'move', who:'barabba', to:[-27.6,-60], speed:0.9, wait:false},
      {t:'cam', from:[-24.6,4.6,-56.4], look:[-27.6,4.2,-60], dur:2},
      {t:'read', ref:'MATTITHYAHU 27:16'},
      {t:'read', ref:'MARK 15:7'},
      {t:'cam', from:[-27,5.4,-55.4], look:'pilate', dur:1.6},
      {t:'say', who:'pilate', ref:'YAHUCHANON 18:39', turn:false},
      {t:'say', who:'yahudim', ref:'YAHUCHANON 18:40', turn:false},
      {t:'read', ref:'MATTITHYAHU 27:18'},
      {t:'move', who:'pilate', to:'throne', speed:1},
      {t:'place', who:'pilate', at:'throne', face:0},
      {t:'sit', who:'pilate'},
      {t:'read', ref:'MATTITHYAHU 27:19', voices:['wife']},
      {t:'move', who:['kg1','kg2'], to:[[-27,-50.4],[-24.4,-51.6]], speed:1, wait:false},
      {t:'cam', from:[-21,4.4,-46], look:'kg1', dur:2.2},
      {t:'read', ref:'MATTITHYAHU 27:20'},
      {t:'cam', from:[-22,6.8,-50], look:[-30,4.4,-55], dur:2},
      {t:'say', voices:['pilate','yahudim'], ref:'MATTITHYAHU 27:22', turn:false},
      {t:'say', voices:['pilate','yahudim'], ref:'MATTITHYAHU 27:23', turn:false},
      {t:'choice', prompt:'The crowd is crying out for Barabba. You', options:[
        {text:'Cry out His name instead', reply:'One voice in all that noise. The man beside you looks at you, and then away, and shouts the louder.'},
        {text:'Say nothing', reply:'You say nothing. Neither does He. Only the crowd is loud.'} ]},
      /* THE COURT (Yahuchanon 19:1; Mattithyahu 27:27-30): what the soldiers did to Him is read, as the
         Besorah tells it; the camera is on them and on the post, and on His back, never on a blow */
      {t:'stand', who:'pilate'},
      {t:'move', who:['yahusha','sold1','sold2'], to:[['palaceIn',0,-1.6],['palaceIn',-1.4,-0.6],['palaceIn',1.4,-0.6]], speed:1},
      {t:'face', who:'yahusha', to:'post'},
      {t:'show', id:['coh0','coh1','coh2','coh3','coh4','coh5']},
      {t:'face', who:'coh0', to:'yahusha'}, {t:'face', who:'coh1', to:'yahusha'}, {t:'face', who:'coh2', to:'yahusha'},
      {t:'face', who:'coh3', to:'yahusha'}, {t:'face', who:'coh4', to:'yahusha'}, {t:'face', who:'coh5', to:'yahusha'},
      {t:'cam', from:{rel:'yahusha', off:[1.9,1.5,3.4]}, look:'yahusha', dur:2.4},
      {t:'note', text:'What was done to Him in the court is told here as the Besorah tells it. It is not shown.'},
      {t:'read', ref:'YAHUCHANON 19:1'},
      {t:'read', ref:'MATTITHYAHU 27:27'},
      {t:'robe', who:'yahusha', color:0xd6c9a8, mantle:0x9a1f26},
      {t:'read', ref:'MATTITHYAHU 27:28'},
      {t:'crown', who:'yahusha'},
      {t:'sit', who:['coh1','coh2','coh4']},
      {t:'read', ref:'MATTITHYAHU 27:29', voices:['soldiers']},
      {t:'stand', who:['coh1','coh2','coh4']},
      {t:'read', ref:'MATTITHYAHU 27:30'},
      {t:'hide', id:['coh0','coh1','coh2','coh3','coh4','coh5']},
      {t:'cam', from:[-22,6.8,-50], look:[-30,4.4,-55], dur:2},
      {t:'stand', who:'pilate'},
      {t:'move', who:'pilate', to:'pavement', speed:1},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:4', turn:false},
      {t:'move', who:'yahusha', to:[-32,-60], speed:0.8},
      {t:'face', who:'yahusha', to:'y4'},
      {t:'cam', on:'yahusha', shot:'back', toward:'y4', back:5, dur:2.4},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:5', turn:false},
      {t:'say', voices:['priests','pilate'], ref:'YAHUCHANON 19:6', turn:false},
      {t:'say', who:'yahudim', ref:'YAHUCHANON 19:7', turn:false},
      {t:'read', ref:'YAHUCHANON 19:8'},
      {t:'face', who:'pilate', to:'yahusha'},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:9', turn:false},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:10', turn:false},
      {t:'cam', on:'yahusha', shot:'back', toward:'pilate', dur:1.6},
      {t:'say', who:'yahusha', ref:'YAHUCHANON 19:11', turn:false},
      {t:'say', who:'yahudim', ref:'YAHUCHANON 19:12', turn:false},
      {t:'move', who:'pilate', to:'throne', speed:1},
      {t:'place', who:'pilate', at:'throne', face:0},
      {t:'sit', who:'pilate'},
      {t:'cam', from:[-34,6.2,-55.6], look:[-38,5,-61.6], dur:2},
      {t:'read', ref:'YAHUCHANON 19:13'},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:14', turn:false},
      {t:'say', voices:['yahudim','pilate','priests'], ref:'YAHUCHANON 19:15', turn:false},
      {t:'stand', who:'pilate'},
      {t:'move', who:'pilate', to:[-35.6,-59.4], speed:0.8},
      {t:'cam', from:[-31.4,5.2,-56.4], look:'pilate', dur:1.8},
      {t:'say', who:'pilate', ref:'MATTITHYAHU 27:24', turn:false},
      {t:'say', who:'people', ref:'MATTITHYAHU 27:25', turn:false},
      {t:'read', ref:'LUKE 23:24'},
      {t:'move', who:'barabba', to:[-22,-51], speed:1.6, wait:false},
      {t:'cam', from:[-24.6,4.6,-56.4], look:'barabba', dur:1.6},
      {t:'read', ref:'LUKE 23:25'},
      {t:'robe', who:'yahusha', color:0xd6c9a8, mantle:0xe9e2cf},
      {t:'move', who:['yahusha','sold1','sold2'], to:[[-11,-41],[-12.2,-42],[-9.8,-42]], speed:0.9, wait:false},
      {t:'cam', from:[-18,7.4,-52], look:[-26,4,-55], dur:3},
      {t:'read', ref:'MATTITHYAHU 27:31'},
      {t:'choice', prompt:'You', options:[
        {text:'Look for a face you know in the crowd', reply:'You find none of the Twelve. You find a man from Kephar Naḥum who ate the bread on the grass. He is shouting with the rest.'},
        {text:'Look at Barabba', reply:'He is walking out through the crowd, rubbing his wrists, not quite believing it. A man who should have died today.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.11 — GOLGOTHA ---------------- */
  { id:'golgotha', title:'Golgotha', date:'the sixth hour', place:'golgotha', time:'day',
    player:{ at:[-57,8], face:Math.PI, look:ADULT },
    crowds:[ {id:'onlookers', n:170, area:[-56,-52,-42,-16], look:'skull', path:[[-56,44],[-56,-58]], clear:1.3} ],
    actors:[
      Object.assign({id:'yahusha', at:'roadBend', face:-Math.PI*0.85, crown:true},YAHUSHA),
      /* stripped of their garments, in a loincloth only (Yahuchanon 19:23-24) */
      Object.assign({id:'yahushaS', at:'onStake', face:Math.PI/2, y:'stakeY', hidden:true, stripped:true, crown:true},YAHUSHA),
      {id:'evil1', name:'An evil-doer', key:'the evil-doer who spoke evil', at:'stakeL', face:Math.PI/2, robe:0x5a4a3a, cloth:0x6a5a44, beard:0x1e1814, hidden:true, stripped:true},
      {id:'evil2', name:'The other evil-doer', key:'the other evil-doer', at:'stakeR', face:Math.PI/2, robe:0x4a3a2a, cloth:0x7a6a54, beard:0x2c241f, hidden:true, stripped:true},
      {id:'kurene', name:'Shim‛on, a Cyrenian', key:'Shim‛on a Cyrenian', at:['roadBend',1.6,2.4], face:-Math.PI*0.85, robe:0x7a6a4a, cloth:0xcfc4aa, beard:0x2c241f},
      LEGION('sold1',['roadBend',-1.4,-2],-Math.PI*0.85), LEGION('sold2',['roadBend',1.8,-1.6],-Math.PI*0.85),
      LEGION('sold3','soldiers',-Math.PI/2), LEGION('sold4',['soldiers',1.2,-1.4],-Math.PI/2),
      {id:'captain', name:'The captain', key:'the captain at the stake', folk:'roman', dress:'centurion', at:['foot',2,3.6], face:-Math.PI/2},
      Object.assign({id:'miryam', at:['afar',-1,-1], face:-Math.PI*0.75},MIRYAM),
      T('yahuchanon',['afar',0.6,-2.2],{face:-Math.PI*0.75}),
      {id:'magdala', name:'Miryam from Maḡdala', key:'Miryam from Magdala', kind:'woman', at:['afar',1.6,0.8], face:-Math.PI*0.75, robe:0x6a3a4a, cloth:0x3c3a44, skin:0x7a4e30},
      {id:'qlophah', name:'Miryam the wife of Qlophah', key:'Miryam the wife of Qlophah', kind:'woman', at:['afar',-0.4,1.6], face:-Math.PI*0.75, robe:0x5a5a3a, cloth:0x2e2a30, skin:0x7c5430},
      ...PLOTTERS.map((a,k)=>Object.assign({},a,{at:['scoffers',k*1.6,-1.2], face:-Math.PI/2})),
      ...ROADFOLK
    ],
    things:[ {id:'beam', kind:'box', at:['roadBend',1.6,2.4], w:0.22, h:0.22, d:3.2, color:0x6e5238},
             /* His garments, in a heap where the soldiers sit to cast lots for them */
             {id:'garments', kind:'box', at:['soldiers',0.9,0.7], w:0.8, h:0.16, d:0.6, color:0xd6c9a8, hidden:true},
             {id:'tunic', kind:'box', at:['soldiers',-0.3,1.3], w:0.5, h:0.1, d:0.7, color:0xcfc2a0, hidden:true} ],
    beats:[
      {t:'lead', id:'beam', by:'kurene', back:0.1, up:1.45, turn:Math.PI/2},
      {t:'cam', from:[-50,6,10], look:[-62,2,-24], dur:0.1},
      {t:'move', who:['yahusha','kurene','sold1','sold2'], to:[['foot',2.4,0],['foot',4.6,1.6],['foot',3,-2],['foot',4.4,-1.2]], speed:1.1, wait:false},
      {t:'follow', who:ids(ROADFOLK).slice(0,6).concat(['miryam','yahuchanon','magdala','qlophah']), target:'yahusha'},
      {t:'read', ref:'LUKE 23:26'},
      {t:'read', ref:'LUKE 23:27'},
      {t:'stop', who:['yahusha']},
      {t:'face', who:'yahusha', to:'magdala'},
      {t:'cam', on:'yahusha', shot:'back', toward:'magdala', dur:1.8},
      {t:'say', who:'yahusha', ref:'LUKE 23:28', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 23:29', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 23:30', turn:false},
      {t:'say', who:'yahusha', ref:'LUKE 23:31', turn:false},
      {t:'move', who:['yahusha','kurene','sold1','sold2'], to:[['foot',0.6,0],['foot',2.2,1.6],['foot',1,-2],['foot',2.4,-1.2]], speed:0.7},
      {t:'lead', id:'beam'}, {t:'hide', id:'beam'},
      {t:'stop', who:ids(ROADFOLK).slice(0,6).concat(['miryam','yahuchanon','magdala','qlophah'])},
      {t:'move', who:['miryam','yahuchanon','magdala','qlophah'], to:[['afar',-1,-1],['afar',0.6,-2.2],['afar',1.6,0.8],['afar',-0.4,1.6]], speed:1, wait:false},
      {t:'read', ref:'LUKE 23:32'},
      {t:'goal', text:'Stand with the women from Galil, at a distance', goto:'afar', r:4},
      {t:'hide', id:'yahusha'},
      {t:'show', id:['yahushaS','evil1','evil2','garments','tunic']},
      {t:'pose', who:['yahushaS','evil1','evil2'], arms:'up'},
      {t:'place', who:'evil1', at:['stakeL',0.3,0], y:'stakeY', face:Math.PI/2}, {t:'place', who:'evil2', at:['stakeR',0.3,0], y:'stakeY', face:Math.PI/2},
      /* the stakes are seen from far off over the city's side (too far for any face), or from
         beside and behind (the pole stands at their backs) — never His face */
      {t:'cam', from:['skull',44,6], fdy:24, look:'yahushaS', dur:0.1},
      {t:'read', ref:'LUKE 23:33'},
      {t:'cam', from:{rel:'yahushaS', off:[-1.3,1.1,3.3]}, look:'yahushaS', dur:3},
      {t:'say', who:'yahushaS', ref:'LUKE 23:34', turn:false},
      {t:'read', ref:'YAHUCHANON 19:19'},
      {t:'read', ref:'YAHUCHANON 19:20'},
      {t:'say', who:'priests', ref:'YAHUCHANON 19:21'},
      {t:'say', who:'pilate', ref:'YAHUCHANON 19:22'},
      {t:'cam', from:['soldiers',4.6,3.2], fdy:2.2, look:'sold3', dur:2},
      {t:'sit', who:['sold3','sold4']},
      {t:'read', ref:'YAHUCHANON 19:23'},
      {t:'say', voices:['soldiers','psalmist'], ref:'YAHUCHANON 19:24', turn:false},
      {t:'cam', from:['scoffers',3.4,3], fdy:1.8, look:'kg1', dur:2},
      {t:'say', who:'rulers', ref:'LUKE 23:35', turn:false},
      {t:'say', who:'soldiers', ref:'LUKE 23:36-37', turn:false},
      {t:'read', ref:'LUKE 23:38'},
      {t:'cam', from:['skull',-3.4,8.8], fdy:5.4, look:'evil2', dur:2},
      {t:'say', who:'evil1', ref:'LUKE 23:39', turn:false},
      {t:'say', who:'evil2', ref:'LUKE 23:40-41', turn:false},
      {t:'say', who:'evil2', ref:'LUKE 23:42', turn:false},
      {t:'say', who:'yahushaS', ref:'LUKE 23:43', turn:false},
      {t:'move', who:['miryam','yahuchanon','magdala','qlophah'], to:['mother',['mother',1.2,-0.6],['mother',0.6,1.2],['mother',1.8,0.8]], speed:0.8},
      {t:'cam', from:['skull',-3,7.4], fdy:4.4, look:'mother', dur:2.5},
      {t:'read', ref:'YAHUCHANON 19:25'},
      {t:'say', who:'yahushaS', ref:'YAHUCHANON 19:26', turn:false},
      {t:'say', who:'yahushaS', ref:'YAHUCHANON 19:27', turn:false},
      {t:'time', to:'darkness'},
      {t:'cam', from:['skull',-8,12], fdy:6, look:'yahushaS', dur:4},
      {t:'read', ref:'MARK 15:33'},
      {t:'say', who:'yahushaS', ref:'MARK 15:34', turn:false},
      {t:'say', who:'standers', ref:'MARK 15:35', turn:false},
      {t:'say', who:'someone', ref:'MARK 15:36', turn:false},
      {t:'say', who:'yahushaS', ref:'YAHUCHANON 19:28', turn:false},
      {t:'read', ref:'YAHUCHANON 19:29'},
      {t:'cam', from:{rel:'yahushaS', off:[-1.3,1.1,3.3]}, look:'yahushaS', dur:3},
      {t:'say', who:'yahushaS', ref:'YAHUCHANON 19:30', turn:false},
      {t:'fulfil', id:'y53-5'},
      /* "and see, the veil of the Dwelling Place was torn in two … and the earth was shaken, and the
         rocks were split": from behind the stakes, over the city to the House */
      {t:'cam', from:['skull',-5,1], fdy:6, look:[6,24,-44], dur:3, wait:false},
      {t:'quake', s:4},
      {t:'time', to:'dusk'},
      {t:'read', ref:'MATTITHYAHU 27:51'},
      {t:'cam', from:['captain',2.6,2.6], fdy:1.8, look:'captain', dur:2},
      {t:'say', who:'captain', ref:'MARK 15:39', turn:false},
      {t:'move', who:ids(ROADFOLK).concat(['kg1','kg2']), to:ROADFOLK.concat(PLOTTERS).map((a,k)=>[-59+(k%3)*1.4,2+Math.floor(k/3)*1.4]), speed:1, wait:false},
      {t:'cam', from:{rel:'evil1', off:[-5,1.4,-6]}, look:['afar',0,0], dur:3},
      {t:'read', ref:'LUKE 23:48'},
      {t:'hide', id:'onlookers'},
      {t:'read', ref:'LUKE 23:49'},
      {t:'cam', release:true},
      {t:'choice', prompt:'You', options:[
        {text:'Say the words of your family’s scroll', reply:'“He was pierced for our transgressions, crushed for our crookednesses.” Your father’s fathers copied it out seven hundred years ago. You have just watched it.'},
        {text:'Stay where you are, with the women', reply:'Nobody speaks. His mother has not moved. You stay until the light goes.'} ]},
      {t:'end'}
    ]},

  /* ---------------- VI.12 — THE TOMB IN THE GARDEN ---------------- */
  { id:'tomb', title:'The garden', date:'the Preparation, toward evening', place:'golgotha', time:'dusk',
    player:{ at:'garden', face:-Math.PI/2, look:ADULT },
    actors:[
      Object.assign({id:'yahushaS', at:'onStake', face:Math.PI/2, y:'stakeY', stripped:true, crown:true},YAHUSHA),
      {id:'body', name:'', dress:'wrapped', holy:true, at:'tombOut', face:-Math.PI/2, hidden:true},
      {id:'yoseph', name:'Yosĕph of Ramathayim', key:'Yoseph of Ramathayim', at:['gateRoad',-20,-30], face:-Math.PI*0.8, robe:0x3a3a5a, cloth:0xe6e0cf, sash:0xb08d3c, beard:0x6d6a66, kind:'oldman'},
      {id:'nakdimon', name:'Naḵdimon', key:'Nakdimon', at:['garden',4,4], face:-Math.PI/2, robe:0x5a3a2a, cloth:0xe6dcc0, beard:0x6d6a66, kind:'oldman'},
      {id:'magdala', name:'Miryam from Maḡdala', key:'Miryam from Magdala', kind:'woman', at:['opposite',0,-1.2], face:-Math.PI/2, robe:0x6a3a4a, cloth:0x3c3a44, skin:0x7a4e30},
      {id:'qlophah', name:'The other Miryam', key:'Miryam the wife of Qlophah', kind:'woman', at:['opposite',0.4,0.6], face:-Math.PI/2, robe:0x5a5a3a, cloth:0x2e2a30, skin:0x7c5430},
      LEGION('guard1',['tombFront',0,-2.4],Math.PI/2,{hidden:true}), LEGION('guard2',['tombFront',0,2.4],Math.PI/2,{hidden:true})
    ],
    things:[ {id:'stone', kind:'roundStone', at:'stone', face:0, r:1.25},
             {id:'spices', kind:'jar', at:['garden',4.4,5.4]} ],
    glows:[ {id:'seal', at:[-67.6,1.4,-11], size:0.5, color:0xc04030, intensity:0.3, hidden:true} ],
    beats:[
      {t:'pose', who:'yahushaS', arms:'up'},
      {t:'cam', from:['skull',-8,12], fdy:6, look:'yahushaS', dur:0.1},
      {t:'read', ref:'YAHUCHANON 19:31'},
      {t:'read', ref:'YAHUCHANON 19:32'},
      {t:'read', ref:'YAHUCHANON 19:33'},
      {t:'cam', from:['garden',2,2], fdy:2, look:'magdala', dur:2.5},
      {t:'read', ref:'YAHUCHANON 19:34'},
      {t:'read', ref:'YAHUCHANON 19:35'},
      {t:'read', ref:'YAHUCHANON 19:36', voices:['psalmist']},
      {t:'read', ref:'YAHUCHANON 19:37', voices:['psalmist']},
      {t:'move', who:'yoseph', to:['garden',-2,0], speed:1.1, wait:false},
      {t:'cam', from:['garden',6,-4], fdy:2.4, look:'yoseph', dur:3},
      {t:'read', ref:'LUKE 23:50'},
      {t:'read', ref:'LUKE 23:51'},
      {t:'read', ref:'LUKE 23:52'},
      {t:'read', ref:'YAHUCHANON 19:38'},
      {t:'read', ref:'YAHUCHANON 19:39'},
      {t:'witness', text:'Help Naḵdimon carry the myrrh and aloes to the tomb', items:['spices'], verb:'Take up the spices', hold:0.8, deliver:'tombFront', r:2.6, carryText:'Carry them to the tomb in the garden'},
      {t:'hide', id:'yahushaS'},
      {t:'show', id:'body'},
      {t:'lie', who:'body'},
      {t:'move', who:['yoseph','nakdimon'], to:[['tombOut',1.6,-1.6],['tombOut',1.6,1.6]], speed:1},
      {t:'cam', from:['tombFront',3,-3], fdy:2, look:'tombOut', dur:2.5},
      {t:'read', ref:'YAHUCHANON 19:40'},
      {t:'read', ref:'YAHUCHANON 19:41'},
      {t:'read', ref:'YAHUCHANON 19:42'},
      {t:'place', who:'body', at:'tombIn', face:-Math.PI/2},
      {t:'read', ref:'LUKE 23:53'},
      {t:'cam', release:true},
      {t:'witness', text:'Put your shoulder to the stone with Yosĕph', items:['stone'], verb:'Roll the stone across the door', hold:1.6, reach:3, send:'stoneShut'},
      {t:'cam', from:['tombFront',4,3], fdy:2, look:'tomb', dur:2.5},
      {t:'read', ref:'MATTITHYAHU 27:60'},
      {t:'sit', who:['magdala','qlophah']},
      {t:'read', ref:'MATTITHYAHU 27:61'},
      {t:'read', ref:'LUKE 23:54'},
      {t:'read', ref:'LUKE 23:55'},
      {t:'read', ref:'LUKE 23:56'},
      {t:'time', to:'night'},
      {t:'note', text:'The next day was the Shabbath.'},
      {t:'read', ref:'MATTITHYAHU 27:62'},
      {t:'say', who:'seekers', ref:'MATTITHYAHU 27:63-64'},
      {t:'say', who:'pilate', ref:'MATTITHYAHU 27:65'},
      {t:'show', id:['guard1','guard2','seal']},
      {t:'cam', from:['tombFront',5,0], fdy:2.4, look:'tomb', dur:3},
      {t:'read', ref:'MATTITHYAHU 27:66'},
      {t:'choice', prompt:'You', options:[
        {text:'Look at the sealed stone', reply:'You pushed it there yourself. It is very heavy, and now there is a seal on it and Romans in front of it.'},
        {text:'Remember the words in Galil', reply:'“After I am raised, I shall go before you to Galil.” He said it on the way to the garden. You did not understand it then. You do not understand it now.'} ]},
      {t:'title', text:'The end of Act VI', sub:'Next: The Rising'},
      {t:'end'}
    ]}

  ]
});
})();
