# python3 -I convert.py DEMDIR OUT.js — terrarium tiles → world/dem.js (int16 metres, row-delta, raw deflate, base64)
import sys, os, zlib, base64, json
import numpy as np
from PIL import Image
dem,out=sys.argv[1],sys.argv[2]
LAYERS=[(4,0,15,0,15,2),(9,303,308,203,212,1),(10,609,614,410,419,1),(12,2447,2449,1665,1667,1)]
res=[]; total=0
for z,x0,x1,y0,y1,step in LAYERS:
    W=(x1-x0+1)*256; H=(y1-y0+1)*256
    A=np.zeros((H,W),dtype=np.float64)
    for x in range(x0,x1+1):
        for y in range(y0,y1+1):
            im=np.asarray(Image.open(f"{dem}/{z}/{x}/{y}.png").convert('RGB')).astype(np.float64)
            e=im[:,:,0]*256+im[:,:,1]+im[:,:,2]/256-32768
            A[(y-y0)*256:(y-y0+1)*256,(x-x0)*256:(x-x0+1)*256]=e
    if step>1:   # the global layer: averaged down
        A=A.reshape(H//step,step,W//step,step).mean(axis=(1,3)); H//=step; W//=step
    # the deep below 500 m is kept to 25 m (nobody stands on it); the land and the shallows to the metre
    A=np.where(A<-500,np.round(A/25)*25,A)   # (the Salt Sea's shore is at -430: nothing above -500 is rounded)
    q=np.clip(np.round(A),-11000,9000).astype(np.int32)
    # planar prediction: each sample less (left + above - above-left); the first row and column by row/column delta
    d=q.copy(); d[1:,1:]=q[1:,1:]-(q[1:,:-1]+q[:-1,1:]-q[:-1,:-1]); d[0,1:]=q[0,1:]-q[0,:-1]; d[1:,0]=q[1:,0]-q[:-1,0]
    raw=d.astype('<i2').tobytes()
    c=zlib.compressobj(9,zlib.DEFLATED,-15); comp=c.compress(raw)+c.flush()
    b=base64.b64encode(comp).decode('ascii'); total+=len(b)
    res.append({'z':z,'x0':x0*256//step,'y0':y0*256//step,'w':W,'h':H,'s':step,'min':int(q.min()),'max':int(q.max()),'b':b})
    print('layer z%d %dx%d step%d min %d max %d -> %.2f MB'%(z,W,H,step,q.min(),q.max(),len(b)/1e6))
with open(out,'w') as f:
    f.write('/* THE TRUE FACE OF THE EARTH — heights and depths in metres, from the open Terrain Tiles\n')
    f.write('   (Mapzen / AWS Open Data: SRTM, GMTED, ETOPO1 and others; see CREDITS in PLAY-LOCALLY.md).\n')
    f.write('   Each layer is a block of web-mercator tiles at zoom z: w×h samples whose (0,0) is pixel (x0,y0)\n')
    f.write('   of the whole world at that zoom (at s pixels to a sample), each the planar remainder (less left + above − above-left) of 16-bit metres,\n')
    f.write('   raw-deflated, base64. Read by js/dem.js. Generated by tools/dem/convert.py. */\n')
    f.write('window.EARTH=window.EARTH||{}; EARTH.dem={layers:[\n')
    for L in res:
        f.write('{z:%d,x0:%d,y0:%d,w:%d,h:%d,s:%d,min:%d,max:%d,b:"%s"},\n'%(L['z'],L['x0'],L['y0'],L['w'],L['h'],L['s'],L['min'],L['max'],L['b']))
    f.write(']};\n')
print('total %.2f MB'%(total/1e6))
